# Generated by Django 2.2.4 on 2019-10-03 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactApp', '0003_auto_20191001_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='birth',
            field=models.DateField(default='2019-10-03', max_length=20, verbose_name='出生日期'),
        ),
    ]
